[build]
  publish = "website/public"
  command = "pushd website; hugo --gc --minify; popd"

  [build.environment]
    HUGO_VERSION = "0.120.3"

[context.production.environment]
  HUGO_ENV           = "production"
  HUGO_ENABLEGITINFO = "true"
